### ISSUE TITLE
[BUG] System.IO.IOException: Access to the path '\\?\C:\Users\GSP\AppData\Local\Bloxstrap\Roblox\Player.old\content\textures' is denied.

### ISSUE THREAD

**Issue by EstrelarX** [bloxstraplabs/bloxstrap#3942] opened 2024-12-08 00:06 UTC
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.1

### What problem did you encounter?

help me i cant use blox trap cuz of this 
![ioa](https://github.com/user-attachments/assets/5865575d-7173-4b75-be6e-a1117cf9448c)

### Bloxstrap Log

```text
N/A
```

**Comment by Storm-930** [comment] 2024-12-08 10:13
Duplicate of issue #3895

**Comment by bluepilledgreat** [comment] 2024-12-08 11:36
^^^

**Closed by bluepilledgreat** 2024-12-08 11:36 UTC
