### ISSUE TITLE
[BUG] failed to launch

### ISSUE THREAD

**Issue by bob1323** [bloxstraplabs/bloxstrap#3277] opened 2024-10-17 19:00 UTC
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

bloxstrap says roblox failed to launch and after a minute it launches and its really annoying because my web broswer opens and it takes A MINUTE

### Bloxstrap Log

N/A

**Comment by pizzaboxer** [comment] 2024-10-17 19:03
Duplicate of #3176 

Just a moment, how long does it take for Roblox to open normally?

**Comment by bob1323** [comment] 2024-10-20 23:34
when it normally opens without error it takes like 2 seconds

**Comment by pizzaboxer** [comment] 2024-10-24 23:12
Thanks for reporting

**Closed by pizzaboxer** 2024-10-24 23:12 UTC
