### ISSUE TITLE
[BUG] System.UnauthorizedAccessException: Access to the path 'Arimo-Bold.ttf' is denied.

### ISSUE THREAD

**Issue by bubterminator101** [bloxstraplabs/bloxstrap#3428] opened 2024-10-23 22:16 UTC
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.0

### What problem did you encounter?

![image_2024-10-23_181459734](https://github.com/user-attachments/assets/d747ecad-9d87-4470-8377-82bcf87b7abf)

for some reason, when ever bloxstrap tries to update, this error pops up, im not sure whats wrong.

### Bloxstrap Log

```text
2024-10-23T22:06:01Z [App::OnStartup] Starting Bloxstrap v2.8.0
2024-10-23T22:06:01Z [App::OnStartup] Compiled Wednesday, 16 October 2024 at 5:44:37 AM from commit 42ffec26cf2e080fe22210305a08fcb286aeb577 (tag/v2.8.0)
2024-10-23T22:06:01Z [App::OnStartup] Loaded from %UserProfile%\AppData\Local\Bloxstrap\Bloxstrap.exe
2024-10-23T22:06:01Z [App::OnStartup] Temp path is %UserProfile%\AppData\Local\Temp\Bloxstrap
2024-10-23T22:06:01Z [App::OnStartup] WindowsStartMenu path is %UserProfile%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs
2024-10-23T22:06:01Z [LaunchSettings] Identifier 'player' is active with data
2024-10-23T22:06:01Z [Logger::Initialize] Initializing at %UserProfile%\AppData\Local\Bloxstrap\Logs\Bloxstrap_20241023T220601Z.log
2024-10-23T22:06:01Z [Logger::Initialize] Finished initializing!
2024-10-23T22:06:01Z [JsonManager<Settings>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Settings.json...
2024-10-23T22:06:01Z [JsonManager<Settings>::Load] Loaded successfully!
2024-10-23T22:06:01Z [JsonManager<State>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\State.json...
2024-10-23T22:06:01Z [JsonManager<State>::Load] Loaded successfully!
2024-10-23T22:06:01Z [FastFlagManager::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Modifications\ClientSettings\ClientAppSettings.json...
2024-10-23T22:06:01Z [FastFlagManager::Load] Loaded successfully!
2024-10-23T22:06:01Z [LaunchHandler::LaunchRoblox] Initializing bootstrapper
2024-10-23T22:06:01Z [LaunchHandler::LaunchRoblox] Initializing bootstrapper dialog
2024-10-23T22:06:01Z [Bootstrapper::Run] Running bootstrapper
2024-10-23T22:06:01Z [Bootstrapper::SetStatus] Connecting to Roblox...
2024-10-23T22:06:01Z [Deployment::TestConnection<https://setup.rbxcdn.com>] Connecting...
2024-10-23T22:06:01Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/versionStudio
2024-10-23T22:06:01Z [Deployment::InitializeConnectivity] Testing connectivity...
2024-10-23T22:06:01Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/versionStudio
2024-10-23T22:06:01Z [Deployment::InitializeConnectivity] Got https://setup.rbxcdn.com as the optimal base URL
2024-10-23T22:06:01Z [Bootstrapper::Run] Connectivity check finished
2024-10-23T22:06:01Z [Bootstrapper::CheckForUpdates] Checking for updates...
2024-10-23T22:06:01Z [HttpClientLoggingHandler::ProcessRequest] GET https://api.github.com/repos/bloxstraplabs/bloxstrap/releases/latest
2024-10-23T22:06:01Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://api.github.com/repos/bloxstraplabs/bloxstrap/releases/latest
2024-10-23T22:06:01Z [Bootstrapper::CheckForUpdates] No updates found
2024-10-23T22:06:01Z [Bootstrapper::GetLatestVersionInfo] Got channel as production
2024-10-23T22:06:01Z [Deployment::GetInfo] Getting deploy info for channel production
2024-10-23T22:06:01Z [HttpClientLoggingHandler::ProcessRequest] GET https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer
2024-10-23T22:06:02Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer
2024-10-23T22:06:02Z [RegistryKeyEx::SetValueSafe] Writing '' to HKEY_CURRENT_USER\SOFTWARE\ROBLOX Corporation\Environments\RobloxPlayer\Channel\www.roblox.com
2024-10-23T22:06:02Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-4e3b062d6e584043-rbxPkgManifest.txt
2024-10-23T22:06:02Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-4e3b062d6e584043-rbxPkgManifest.txt
2024-10-23T22:06:02Z [Bootstrapper::SetStatus] Upgrading {product}...
2024-10-23T22:06:02Z [LaunchHandler::LaunchRoblox] Bootstrapper task has finished
2024-10-23T22:06:02Z [LaunchHandler::LaunchRoblox] An exception occurred when running the bootstrapper
2024-10-23T22:06:02Z [App::FinalizeExceptionHandling] System.UnauthorizedAccessException: Access to the path 'Arimo-Bold.ttf' is denied.
   at System.IO.FileSystem.RemoveDirectoryRecursive(String fullPath, WIN32_FIND_DATA& findData, Boolean topLevel)
   at System.IO.FileSystem.RemoveDirectory(String fullPath, Boolean recursive)
   at Bloxstrap.Bootstrapper.UpgradeRoblox()
   at Bloxstrap.Bootstrapper.Run()
   at Bloxstrap.Bootstrapper.Run()
```

**Comment by bubterminator101** [comment] 2024-10-23 22:40
ok well...i reinstalled bloxstrap and it works fine now.

**Comment by pizzaboxer** [comment] 2024-10-25 22:46
Duplicate of #3408

**Closed by pizzaboxer** 2024-10-25 22:46 UTC
