### ISSUE TITLE
[BUG] my characters models are grey and everyone have no head,also cursor is invisible now 

### ISSUE THREAD

**Issue by KIRILLMINVE** [bloxstraplabs/bloxstrap#3702] opened 2024-11-07 17:25 UTC
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.1

### What problem did you encounter?

when i launch bloxstrap i have invisible cursor and my characters models are grey and the yhave no head

### Bloxstrap Log

```text
N/A
```

**Comment by pizzaboxer** [comment] 2024-11-09 19:15
Duplicate of #3691

**Closed by pizzaboxer** 2024-11-09 19:15 UTC
