### ISSUE TITLE
[REQ] Dark mode for menu, light mode for launcher.

### ISSUE THREAD

**Issue by lossycompressed** [bloxstraplabs/bloxstrap#2699] opened 2024-08-21 01:21 UTC
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

Modes should be separate, as it's nice aesthetic-wise.

**Comment by bluepilledgreat** [comment] 2024-10-27 15:16
Duplicate of #1248

**Closed by bluepilledgreat** 2024-10-27 15:16 UTC
Labels: enhancement
