### ISSUE TITLE
[BUG] Graphics slider wont work

### ISSUE THREAD

**Issue by Oyasumii14** [bloxstraplabs/bloxstrap#3433] opened 2024-10-24 04:59 UTC
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.0

### What problem did you encounter?

Roblox graphics bar doesn't work and i can see it's on the maximum ones because it has AO and the render distance is longer than what i used to, is there any fixes? 

(NOTE: I didn't reinstall Bloxstrap yet so this might get fixed)

### Bloxstrap Log

```text
N/A
```

**Comment by bluepilledgreat** [comment] 2024-10-24 06:28
Does this happen with the regular Roblox bootstrapper?

**Comment by pizzaboxer** [comment] 2024-10-24 23:33
Duplicate of #3426

**Closed by pizzaboxer** 2024-10-24 23:33 UTC
Labels: clarification needed
