### ISSUE TITLE
[BUG] preferred escape menu version not staying at 2023 (V4)   

### ISSUE THREAD

**Issue by jexmaster** [bloxstraplabs/bloxstrap#3336] opened 2024-10-19 11:35 UTC
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

every time I swap the Escape menu version to 2023(V4)  and switch to another setting  it always swaps back to default. 

### Bloxstrap Log

```text
N/A
```

**Comment by NabHeyka22** [comment] 2024-10-19 11:36
What version are you using?

**Comment by NabHeyka22** [comment] 2024-10-19 11:37
Did you check that Bloxstrap is running?

**Comment by jexmaster** [comment] 2024-10-19 11:37
yes

**Comment by NabHeyka22** [comment] 2024-10-19 11:37
Add this fflag:
{
"FFlagEnableInGameMenuChromeABTest3": "False"
}

**Comment by jexmaster** [comment] 2024-10-19 11:38
i have but i dosent work

**Comment by NabHeyka22** [comment] 2024-10-19 11:38
Weird. You may be cooked.

**Comment by jexmaster** [comment] 2024-10-19 11:39
what da flip

**Comment by DionBlox1** [comment] 2024-10-19 12:42
Does this happen? 
[2024-10-19 13-39-09.zip](https://github.com/user-attachments/files/17445241/2024-10-19.13-39-09.zip)

**Comment by pizzaboxer** [comment] 2024-10-19 13:19
> "and switch to another setting it"

Sorry, can you clarify where you're doing this? In Bloxstrap Settings or ingame?

**Comment by saintstanding** [comment] 2024-10-19 13:53
> > "and switch to another setting it"
> 
> Sorry, can you clarify where you're doing this? In Bloxstrap Settings or ingame?

Just wanna say I'm having the same problem here's a clip sorry if its a little long

https://saintstanding.tixte.co/Blox_Strap.mp4

**Comment by Wanwood1** [comment] 2024-10-19 18:40
When you change the menu version, dont go into another tab, i dont know what causes this but aslong as you change the menu version, save it and then dont change the tab it will not go to default

**Comment by saintstanding** [comment] 2024-10-19 20:48
I did try this a lot with test it doesn't work still goes to default

**Comment by jexmaster** [comment] 2024-10-20 15:16
> When you change the menu version, dont go into another tab, i dont know what causes this but aslong as you change the menu version, save it and then dont change the tab its on in the bloxstrap menu it will not go to default

I tried and it doesn't for me either

**Comment by neonboy1** [comment] 2024-10-20 15:17
> I did try this a lot also did with test it doesn't work still goes to default when I load into roblox

same here

**Comment by pizzaboxer** [comment] 2024-10-24 23:15
Duplicate of #3320

**Closed by pizzaboxer** 2024-10-24 23:15 UTC
