### ISSUE TITLE
Connectivity error with bloxstrap, says roblox needs to be installed or updated but I have done so many times.

### ISSUE THREAD

**Issue by Owen-Zeng** [bloxstraplabs/bloxstrap#3378] opened 2024-10-21 01:20 UTC
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.0

### What problem did you encounter?

![image](https://github.com/user-attachments/assets/e988fba2-869e-4b98-993d-df679589062b)

Whenever I try opening an instance, the "connecting to roblox" window shows up, with the connectivity error window popping up right after, and I am unable to open roblox. This has happened suddenly, and I have tried downloading roblox again, but it doesn't work. Roblox works fine without bloxstrap, but I am unable to run it with bloxstap since this error occurs.

### Bloxstrap Log

```text
N/A
```

**Comment by VICK1365** [comment] 2024-10-21 02:36
Same here 
![image](https://github.com/user-attachments/assets/b4838bb0-582e-46c1-a35b-b1400bd01ea0)

**Comment by pizzaboxer** [comment] 2024-10-22 10:13
Duplicate of #3374, we're looking into it

**Closed by pizzaboxer** 2024-10-22 10:13 UTC
