### ISSUE TITLE
[BUG] System.IO.IOException: Access to the path '\\?\C:\Users\ADMIN\AppData\Local\Bloxstrap\Roblox\Player\PlatformContent\pc\fonts' is denied.

### ISSUE THREAD

**Issue by nothingwithmybody** [bloxstraplabs/bloxstrap#3411] opened 2024-10-23 10:45 UTC
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

2.8

### What problem did you encounter?

Bloxtrap Exception make me angry and i can't play 😡😡😡

### Bloxstrap Log

```text
2024-10-23T10:41:28Z [App::OnStartup] Starting Bloxstrap v2.8.0
2024-10-23T10:41:28Z [App::OnStartup] Compiled Wednesday, 16 October 2024 at 4:44:37 PM from commit 42ffec26cf2e080fe22210305a08fcb286aeb577 (tag/v2.8.0)
2024-10-23T10:41:28Z [App::OnStartup] Loaded from %UserProfile%\AppData\Local\Bloxstrap\Bloxstrap.exe
2024-10-23T10:41:28Z [App::OnStartup] Temp path is %UserProfile%\AppData\Local\Temp\Bloxstrap
2024-10-23T10:41:28Z [App::OnStartup] WindowsStartMenu path is %UserProfile%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs
2024-10-23T10:41:28Z [LaunchSettings] Identifier 'player' is active
2024-10-23T10:41:28Z [Logger::Initialize] Initializing at %UserProfile%\AppData\Local\Bloxstrap\Logs\Bloxstrap_20241023T104128Z.log
2024-10-23T10:41:28Z [Logger::Initialize] Finished initializing!
2024-10-23T10:41:29Z [JsonManager<Settings>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Settings.json...
2024-10-23T10:41:29Z [JsonManager<Settings>::Load] Loaded successfully!
2024-10-23T10:41:29Z [JsonManager<State>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\State.json...
2024-10-23T10:41:29Z [JsonManager<State>::Load] Loaded successfully!
2024-10-23T10:41:29Z [FastFlagManager::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Modifications\ClientSettings\ClientAppSettings.json...
2024-10-23T10:41:29Z [FastFlagManager::Load] Loaded successfully!
2024-10-23T10:41:29Z [LaunchHandler::LaunchRoblox] Initializing bootstrapper
2024-10-23T10:41:29Z [LaunchHandler::LaunchRoblox] Initializing bootstrapper dialog
2024-10-23T10:41:29Z [Bootstrapper::Run] Running bootstrapper
2024-10-23T10:41:29Z [Bootstrapper::SetStatus] Connecting to Roblox...
2024-10-23T10:41:29Z [Deployment::TestConnection<https://setup.rbxcdn.com>] Connecting...
2024-10-23T10:41:29Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/versionStudio
2024-10-23T10:41:29Z [Deployment::InitializeConnectivity] Testing connectivity...
2024-10-23T10:41:30Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/versionStudio
2024-10-23T10:41:30Z [Deployment::InitializeConnectivity] Got https://setup.rbxcdn.com as the optimal base URL
2024-10-23T10:41:30Z [Bootstrapper::Run] Connectivity check finished
2024-10-23T10:41:30Z [Bootstrapper::GetLatestVersionInfo] Got channel as zbinaryhttpbuffullswap
2024-10-23T10:41:30Z [HttpClientLoggingHandler::ProcessRequest] GET https://bloxstraplabs.com/metrics/post?key=robloxChannel&value=zbinaryhttpbuffullswap
2024-10-23T10:41:30Z [Deployment::GetInfo] Getting deploy info for channel zbinaryhttpbuffullswap
2024-10-23T10:41:30Z [HttpClientLoggingHandler::ProcessRequest] GET https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer/channel/zbinaryhttpbuffullswap
2024-10-23T10:41:30Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer/channel/zbinaryhttpbuffullswap
2024-10-23T10:41:30Z [Deployment::GetInfo] Getting deploy info for channel production
2024-10-23T10:41:30Z [HttpClientLoggingHandler::ProcessRequest] GET https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer
2024-10-23T10:41:30Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer
2024-10-23T10:41:30Z [RegistryKeyEx::SetValueSafe] Writing 'zbinaryhttpbuffullswap' to HKEY_CURRENT_USER\SOFTWARE\ROBLOX Corporation\Environments\RobloxPlayer\Channel\www.roblox.com
2024-10-23T10:41:30Z [ApplicationSettings::Fetch.PCClientBootstrapper.zbinaryhttpbuffullswap] Fetching fast flags
2024-10-23T10:41:30Z [HttpClientLoggingHandler::ProcessRequest] GET https://clientsettingscdn.roblox.com/v2/settings/application/PCClientBootstrapper/bucket/zbinaryhttpbuffullswap
2024-10-23T10:41:30Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://clientsettingscdn.roblox.com/v2/settings/application/PCClientBootstrapper/bucket/zbinaryhttpbuffullswap
2024-10-23T10:41:30Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/channel/common/version-6caa55ab5baf41f4-rbxPkgManifest.txt
2024-10-23T10:41:31Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/channel/common/version-6caa55ab5baf41f4-rbxPkgManifest.txt
2024-10-23T10:41:31Z [Bootstrapper::SetStatus] Installing {product}...
2024-10-23T10:41:31Z [LaunchHandler::LaunchRoblox] Bootstrapper task has finished
2024-10-23T10:41:31Z [LaunchHandler::LaunchRoblox] An exception occurred when running the bootstrapper
2024-10-23T10:41:31Z [App::FinalizeExceptionHandling] System.IO.IOException: Access to the path '\\?\%UserProfile%\AppData\Local\Bloxstrap\Roblox\Player\PlatformContent\pc\fonts' is denied.
   at System.IO.FileSystem.RemoveDirectoryRecursive(String fullPath, WIN32_FIND_DATA& findData, Boolean topLevel)
   at System.IO.FileSystem.RemoveDirectory(String fullPath, Boolean recursive)
   at Bloxstrap.Bootstrapper.UpgradeRoblox()
   at Bloxstrap.Bootstrapper.Run()
   at Bloxstrap.Bootstrapper.Run()
```

**Comment by Wanwood1** [comment] 2024-10-23 17:08
Reinstall

**Comment by MrT-tak** [comment] 2024-10-23 17:38
> Reinstall

Probably the best option.

**Comment by nothingwithmybody** [comment] 2024-10-24 06:01
i do it very more time but  it not really working  :(


Vào Th 5, 24 thg 10, 2024 vào lúc 00:38 MrT ***@***.***> đã
viết:

**Comment by MrT-tak** [comment] 2024-10-24 17:24
please select to the modifications folder, with all mods you put in, and try going to properties(ALT+ENTER), security, more security options (or similar, the button above the cancel apply ok buttons) and click on your username. send us the picture.

**Comment by MrT-tak** [comment] 2024-10-24 17:26
hang on, error with the roblox folder? Now, im not sure.

**Comment by nttswannabe** [comment] 2024-10-25 00:16
> Reinstall

reinstalling does not work

**Comment by pizzaboxer** [comment] 2024-10-25 22:44
Duplicate of #3411. I suggest you ensure that you haven't marked any of Roblox's files as read-only, and try restarting.

**Closed by pizzaboxer** 2024-10-25 22:44 UTC
