### ISSUE TITLE
[BUG] System.UnauthorizedAccessException: Access to the path 'RobloxPlayerBeta.exe' is denied.

### ISSUE THREAD

**Issue by spaxz776** [bloxstraplabs/bloxstrap#4188] opened 2024-12-29 23:16 UTC
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.5

### What problem did you encounter?

everytime i try to open blox strap it always tells me "System.UnauthorizedAccessException: Access to the path 'RobloxPlayerBeta.exe' is denied." and im not sure what to do

### Bloxstrap Log

```text
System.UnauthorizedAccessException: Access to the path 'RobloxPlayerBeta.exe' is denied.
```

**Comment by MrT-tak** [comment] 2024-12-30 01:43
Sounds like #4190.
Try seeing that. Maybe a fix is underway.

**Comment by bluepilledgreat** [comment] 2024-12-30 16:09
duplicate of #4190.
there is a fix underway.

**Closed by bluepilledgreat** 2024-12-30 16:09 UTC
