### ISSUE TITLE
[BUG] bloxstrap kinda broke after latest roblox update

### ISSUE THREAD

**Issue by Deexe2137** [bloxstraplabs/bloxstrap#3700] opened 2024-11-07 14:11 UTC
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.1

### What problem did you encounter?

With the latest roblox update bloxstrap has a problem with playermodel not loading, missing ui parts and cursor is completly missing regardless if you're using regular, 2013 or 2006 cursor

![obraz](https://github.com/user-attachments/assets/2222a9f0-a8dd-43f5-b942-f42a7ed05616)

### Bloxstrap Log

```text
N/A
```

**Comment by gamestorer** [comment] 2024-11-07 15:57
Same issue over here.
![image](https://github.com/user-attachments/assets/1000a6cb-d8ad-4843-a23d-1211e2de2c57)
Here's all what F9 gives me - the rest are failed loaded warns.
Having roblox installed on a different drive seems to fix the issue.
![image](https://github.com/user-attachments/assets/32f37f68-7714-4db5-851a-ffb633177041)
Most likely the issue is that roblox freaks out at a cyrillic name. I have no idea how they screwed that up.

**Comment by gamestorer** [comment] 2024-11-07 15:58
> Having roblox installed on a different drive seems to fix the issue.
Nevermind, you cant join games lol

**Comment by structiveAlpha** [comment] 2024-11-07 16:19
Ohhh that's why. My user folder has "ü" in it. You got some info atleast. This could lead to something.

**Comment by IcarusFAith** [comment] 2024-11-07 16:56
I NEED HELP PLEASE, I TRIED EVERYTHING TO FIX IT BUT IT STILL FAILS!!

**Comment by structiveAlpha** [comment] 2024-11-07 17:12
I'm contacting support. Hopefully they respond with something good. Maybe even a fix! I'll tell y'all if they do.

**Comment by yeecie** [comment] 2024-11-07 18:31
Mine is like that too, I've tried everything and it didn't work.

**Comment by PoPcAkOtA** [comment] 2024-11-07 18:50
are u rus?

**Comment by Wanwood1** [comment] 2024-11-09 00:00
Roblox issue

**Comment by pizzaboxer** [comment] 2024-11-09 19:15
Duplicate of #3691

**Comment by pizzaboxer** [comment] 2024-11-09 19:15
Duplicate of #3691

**Closed by pizzaboxer** 2024-11-09 19:15 UTC
