### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Japyxl** [bloxstraplabs/bloxstrap#3481] opened 2024-10-26 00:41 UTC
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.0

### What problem did you encounter?

when ever i alt enter it dont alt enter it just goes into normal full screen and i dont know how to fix that it when i alt enter i can still tab out using f11

**Comment by RyanLua** [comment] 2024-10-26 09:17
Duplicate of #3272

**Closed** 2024-10-29 23:07 UTC
