### ISSUE TITLE
[BUG] When me launch roblox me have loaded only friends

### ISSUE THREAD

**Issue by kilia011014** [bloxstraplabs/bloxstrap#3697] opened 2024-11-07 13:28 UTC
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.0

### What problem did you encounter?

when me load roblox this happened how fix me try redownload roblox but this dont helped (Sorry for bad english)
![image](https://github.com/user-attachments/assets/75154e77-4698-4131-a2d7-310b6d5a8fc9)

### Bloxstrap Log

```text
N/A
```

**Comment by Wanwood1** [comment] 2024-11-07 21:37
Update to latest version and make sure that the drive your bloxstrap is installed in has no special characters, and is from A to Z in latin alphabet.

**Comment by kilia011014** [comment] 2024-11-08 12:16
dont helped :(

**Comment by kilia011014** [comment] 2024-11-08 12:17
> dont helped :(

and now new roblox menu :(

**Comment by Zeradem** [comment] 2024-11-08 16:39
To solve this issue i recommand you to open "Roblox Player" (in right click), go to root folder, find "RobloxPlayerlauncher", and clicking file as an administrator (by right click) and it should work because i had that issue before and i solved that, It's easy to fix.

**Comment by pizzaboxer** [comment] 2024-11-09 19:15
Duplicate of #3691

**Closed by pizzaboxer** 2024-11-09 19:15 UTC

**Comment by kilia011014** [comment] 2024-11-11 14:33
me dont have admin 😢
but roblox fix this
