### ISSUE TITLE
[BUG] min graphic = max, game lags.

### ISSUE THREAD

**Issue by dhd33roblox** [bloxstraplabs/bloxstrap#3447] opened 2024-10-24 15:26 UTC
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.0

### What problem did you encounter?

i cant make graphic in game to lowest, its always maxed, Even if it says its minimum its just visual, i have shadows on minimum graphic and lags.

### Bloxstrap Log

```text
N/A
```

**Comment by NabHeyka22** [comment] 2024-10-24 15:27
i've heard that it's a roblox issue

**Comment by crize1337** [comment] 2024-10-24 15:35
I got this issue today too

**Comment by pizzaboxer** [comment] 2024-10-24 23:35
Duplicate of #3426

**Closed by pizzaboxer** 2024-10-24 23:35 UTC
