### ISSUE TITLE
[BUG] Annoying False error 

### ISSUE THREAD

**Issue by Pineappleisgood11** [bloxstraplabs/bloxstrap#3334] opened 2024-10-19 09:21 UTC
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [x] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

![2024-10-19](https://github.com/user-attachments/assets/ad82fc58-37e8-45d8-b854-54fcf1b93b14)
There's this false error popping up every time I try to use Bloxstrap to launch Roblox, It still launches Roblox and there's no problem while playing Roblox, also my browser opening after closing the error is really annoying.

### Bloxstrap Log

```text
N/A
```

**Comment by NabHeyka22** [comment] 2024-10-19 09:21
It's taking too long to launch.

**Comment by pizzaboxer** [comment] 2024-10-19 12:43
https://github.com/bloxstraplabs/bloxstrap/wiki/%22Roblox-failed-to-launch%22-error-despite-Roblox-launching-fine

Duplicate of #3176

**Closed by pizzaboxer** 2024-10-19 12:43 UTC
