### ISSUE TITLE
[BUG] Is this a bug?

### ISSUE THREAD

**Issue by user1126s** [bloxstraplabs/bloxstrap#3245] opened 2024-10-17 10:25 UTC
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed. (ofc)
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem. (lmao not stable)
- [X] I am using the latest version of Bloxstrap. (way too latest, 9 hours ago build to be precise)

### What problem did you encounter?

![image](https://github.com/user-attachments/assets/6506744a-fc52-43a1-afa4-c93600d1d32e)
Is this gap intentional, a windows issue or a bug? It hurts my eyes but also kinda makes sense as you want the help button to stand out more.

### Bloxstrap Log

N/A

**Comment by user1126s** [comment] 2024-10-17 10:29
### Edit: 
## If this is a bug i want to say that its still there in the latest bloxstrap (debug) version found in the actions tab

**Comment by user1126s** [comment] 2024-10-17 10:39
## Even more edit:
#### In the latest bloxtrap debug version and the bloxstrap debug version (Bloxstrap (Debug)(91f88ca954e3b92d493242f2ddb0d74d2bd11259)) version, specifically in this version PR #3189 by bluepill the great. There is no option for studio and nor the studio shortcut in shortcuts tab. also i think the fflag editor has another invisible tab under shortcuts tab. Let's fix this before it gets to Stable!

**Comment by user1126s** [comment] 2024-10-17 10:44
yea im being too nerdy ik you guys will fix it

**Comment by pizzaboxer** [comment] 2024-10-17 10:52
Duplicate of #3181

**Closed by pizzaboxer** 2024-10-17 10:52 UTC

**Comment by user1126s** [comment] 2024-10-17 10:56
@pizzaboxer

**Comment by pizzaboxer** [comment] 2024-10-17 10:56
Who said studio support was supposed to be released?

**Comment by user1126s** [comment] 2024-10-17 11:16
> Who said studio support was supposed to be released? Do you see it in the release notes?

Looks like i am blind! (my glasses broke)
@pizzaboxer also the query was that there is no studio support in the action tab release that says "Improve studio support". so i thought that. Also just note that you are very good person, because you are so chill after countless of these dumbass issues being made
