### ISSUE TITLE
[BUG] Roblox Failed To Launch, Brings Up Crash Page, Then Launches Fine.

### ISSUE THREAD

**Issue by rozebush** [bloxstraplabs/bloxstrap#3176] opened 2024-10-16 15:06 UTC
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

im not sure how to explain this error other than a general annoyance at worst. everything works fine. however, this error will pop up and open the crash page every time. not sure what would cause this and i know its opening with bloxstrap as the fastflags i have set are applied. this has only started happening after the newest update (2.8.0).
https://github.com/user-attachments/assets/e4a34b78-1782-4612-b2a1-36ca84ef253b

### Bloxstrap Log

N/A

**Comment by notangel1** [comment] 2024-10-16 15:08
me too!!

**Comment by MrT-tak** [comment] 2024-10-16 15:10
Interesting... I had never had this issue before. could the bootstrapping failed so it restarted with the default values?

**Comment by rozebush** [comment] 2024-10-16 15:10
> Interesting... I had never had this issue before. could the bootstrapping failed so it restarted with the default values?

thats what i thought originally, but all the fastflags i set apply when roblox launches so that cant be the case.

**Comment by notangel1** [comment] 2024-10-16 15:12
true i agree roblox had an update one day ago maybe roblox smth changed that's why its causing so many troubles

**Comment by notangel1** [comment] 2024-10-16 15:18
I fixed the problem i opened roblox without bloxstrap (roblox player) i open it then close it and then open bloxstrap again how you do normally and it should work

**Comment by rozebush** [comment] 2024-10-16 15:25
didnt work for me, could you elaborate on the steps? did you open a separate roblox install or the robloxplayerbeta in the bloxstrap player folder?

**Comment by funywiisports** [comment] 2024-10-16 18:25
I get this error too.

**Comment by pizzaboxer** [comment] 2024-10-16 18:29
Will be addressed in the next version. I'll provide a build that gets rid of this issue soon until we can release v2.8.1.

**Comment by TwangyMoney** [comment] 2024-10-22 12:54
Okay, so lets get this straight. This is for the bloxstrap dev team.
After running roblox, on laggier devices it can take upto 2mins for robloxplayerbeta.exe to become a detectable process.
Where sometimes cause of invalid settings or cause of other issues, it can open but not show a UI or enable sounds.
If roblox doesn't open after 2-3 mins of checking, it's usually cause it failed to launch. It would at least be a valid process after 2 mins.
I hope this helps out in updating bloxstrap.

Another thing, for some devices using engines like vulkan or OpenGL can make roblox launch faster and run more smoothly. I suggest remaking the functionality for those engines if it's still possible.

**Comment by pizzaboxer** [comment] 2024-10-24 22:18
>  After running roblox, on laggier devices it can take upto 2mins for robloxplayerbeta.exe to become a detectable process.

If by "detectable process" you mean by the time the Roblox window shows, that's not what we're actually looking for. We're looking for how long it takes for Roblox to create a log file (our threshold is currently at five seconds)

**Comment by TwangyMoney** [comment] 2024-10-25 08:34
> > After running roblox, on laggier devices it can take upto 2mins for robloxplayerbeta.exe to become a detectable process.
> 
> If by "detectable process" you mean by the time the Roblox window shows, that's not what we're actually looking for. We're looking for how long it takes for Roblox to create a log file from the time the process is started (our threshold is currently at five seconds)

No I don't mean by the time the roblox window shows, I mean by the time the process can be found in the task manager. On laggier devices it can take a bit longer for the ui itself to show after that happens. And yes that's definitely long enough for it to create a log file.

**Comment by pizzaboxer** [comment] 2024-10-25 23:05
> No I don't mean by the time the roblox window shows, I mean by the time the process can be found in the task manager. 

That doesn't make any sense?

When you run a process, the process runs. How does a process only show up in Task Manager two minutes after running it? Are you sure you're describing this correctly?

**Comment by pizzaboxer** [comment] 2024-10-25 23:09
Oh also, here's your build: https://github.com/bloxstraplabs/bloxstrap/actions/runs/11526434565/artifacts/2106464097

You guys try this out and let me know if the issue still occurs

**Comment by Migonnes** [comment] 2024-10-28 03:32
My roblox opens in about 14-19 seconds, the seconds change a lot every time I open it, for less or more seconds, even more/less than those I recorded

**Comment by Migonnes** [comment] 2024-10-28 03:41
> Oh also, here's your build: https://github.com/bloxstraplabs/bloxstrap/actions/runs/11526434565/artifacts/2106464097
> 
> You guys try this out and let me know if the issue still occurs

I only tested it once but it seems to be working normally, thanks!

**Comment by Migonnes** [comment] 2024-10-28 03:58
ok i think i find the error for me it was my antivirus bruh

**Comment by Migonnes** [comment] 2024-10-28 05:35
> Oh also, here's your build: https://github.com/bloxstraplabs/bloxstrap/actions/runs/11526434565/artifacts/2106464097
> 
> You guys try this out and let me know if the issue still occurs

thanks i will try

**Comment by Migonnes** [comment] 2024-10-29 01:57
> Oh also, here's your build: https://github.com/bloxstraplabs/bloxstrap/actions/runs/11526434565/artifacts/2106464097
> 
> You guys try this out and let me know if the issue still occurs

In this version the error does not occur! Thank you!

**Comment by TwangyMoney** [comment] 2024-10-29 11:27
> > No I don't mean by the time the roblox window shows, I mean by the time the process can be found in the task manager.
> 
> That doesn't make any sense?
> 
> When you run a process, the process runs. How does a process only show up in Task Manager two minutes after running it? Are you sure you're describing this correctly?

It makes sense, trust me. it has happened many times. If you're unsure feel free to do 1 minute but if some potato pc user tells you to increase it don't ask me.
When I had a laggy pc, it would sometimes take longer for the roblox process to be a valid process. Yes, I counted it. I would count it everytime to find out how long it could take for me to join a game so I can tell my friends.
If you don't trust me it's not an issue. You can do what you think is best.

**Comment by TwangyMoney** [comment] 2024-10-29 11:35
And another thing, statistically using vulkan to run roblox will make it run more quickly and be more smooth. If you check benchmarks online. If you made those possible on bloxstrap again, I know I'm repeating this, then it would really help a lot of people.

Another thing to note, no a process doesn't immediately start logging or become a valid process exactly after it's opened, at least not in laggier devices, you can test it for yourself if you don't trust me.

**Comment by pizzaboxer** [comment] 2024-10-29 23:03
Fixed in 2.8.1 - reopen if not

**Closed by pizzaboxer** 2024-10-29 23:03 UTC
Labels: bug

**Comment by MrT-tak** [comment] 2024-10-31 09:18
@

**Comment by rozebush** [comment] 2024-12-22 19:25
ive discovered after getting a new pc ( fucking finally ) that windowblinds causes the false crash. not having it installed at all causes roblox to open just fine with no error. but if i install it, ( adding flags to not skin roblox as that causes the anti cheat to bug out and close it for some reason ) bloxstrap displays the false crash message. i tried adding flags to not skin bloxstrap as well but that did not do anything.

**Comment by TwangyMoney** [comment] 2024-12-26 16:58
> ive discovered after getting a new pc ( fucking finally ) that windowblinds causes the false crash. not having it installed at all causes roblox to open just fine with no error. but if i install it, ( adding flags to not skin roblox as that causes the anti cheat to bug out and close it for some reason ) bloxstrap displays the false crash message. i tried adding flags to not skin bloxstrap as well but that did not do anything.

We know what the issue is, it's cause the timeout is set too low. Installed programs make computers lag and that lag makes it so the log doesn't become available within that timeout. And what you're saying here can't be fixed with removing flags.

**Comment by rozebush** [comment] 2024-12-27 00:46
> > ive discovered after getting a new pc ( fucking finally ) that windowblinds causes the false crash. not having it installed at all causes roblox to open just fine with no error. but if i install it, ( adding flags to not skin roblox as that causes the anti cheat to bug out and close it for some reason ) bloxstrap displays the false crash message. i tried adding flags to not skin bloxstrap as well but that did not do anything.
> 
> We know what the issue is, it's cause the timeout is set too low. Installed programs make computers lag and that lag makes it so the log doesn't become available within that timeout. And what you're saying here is wrong and it can't be fixed with removing flags (tho sometimes some flags can help reduce lag or, even increase lag).

im not saying the flags will fix the issue. im saying that skinning roblox with windowblinds causes it to crash, regardless of bloxstrap. just adding my findings in case it helps with the issue at all.

**Comment by TwangyMoney** [comment] 2024-12-27 07:32
> > > ive discovered after getting a new pc ( fucking finally ) that windowblinds causes the false crash. not having it installed at all causes roblox to open just fine with no error. but if i install it, ( adding flags to not skin roblox as that causes the anti cheat to bug out and close it for some reason ) bloxstrap displays the false crash message. i tried adding flags to not skin bloxstrap as well but that did not do anything.
> > 
> > 
> > We know what the issue is, it's cause the timeout is set too low. Installed programs make computers lag and that lag makes it so the log doesn't become available within that timeout. And what you're saying here is wrong and it can't be fixed with removing flags (tho sometimes some flags can help reduce lag or, even increase lag).
> 
> im not saying the flags will fix the issue. im saying that skinning roblox with windowblinds causes it to crash, regardless of bloxstrap. just adding my findings in case it helps with the issue at all.

that's more fair 👍
