### ISSUE TITLE
[BUG] "Error Launching" even though it launches just fine

### ISSUE THREAD

**Issue by ilmrx** [bloxstraplabs/bloxstrap#3292] opened 2024-10-17 23:27 UTC
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

I got the error saying it couldn't launch yet it proceeds to launch normally. This is from the latest version

### Bloxstrap Log

N/A

**Comment by pizzaboxer** [comment] 2024-10-18 13:09
Duplicate of #3176

**Closed by pizzaboxer** 2024-10-18 13:09 UTC
