### ISSUE TITLE
[REQ] Multi Instances

### ISSUE THREAD

**Issue by ihatelifebecauseofthisonething** [bloxstraplabs/bloxstrap#3338] opened 2024-10-19 14:09 UTC
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

Add back the multi instances. I really liked that feature. It was useful most of the time.

**Comment by NabHeyka22** [comment] 2024-10-19 14:10
Pizzaboxer won't add multi instance, as people use it to farm in games.

**Comment by pizzaboxer** [comment] 2024-10-19 20:48
Duplicate of #3276

**Closed by pizzaboxer** 2024-10-19 20:48 UTC
