### ISSUE TITLE
[REQ] FastFlag Saves/Configs

### ISSUE THREAD

**Issue by HarmonicDust** [bloxstraplabs/bloxstrap#3283] opened 2024-10-17 20:08 UTC
### Acknowledgement of preliminary instructions

- [X] I have read and acknowledged the preliminary instructions.

### What idea do you have?

Sometimes, you want different fast flags in different games, like specific lighting in one game, specific values disabled in others, etc. Simply using a dropdown with all your saved fast flags, you can choose which ones to deploy

Here's a demo of how this would probably be formatted and saved (note: the fast flags used are for demonstration purposes only!!!)
```json
{
    "WonderfulLighting": {
        "DFlagImFedUp": "True",
        "FFlagHandleAltEnterFullscreenManually": "False",
        "FFlagDebugGraphicsPreferD3D11": "True",
        "FFlagFixGraphicsQuality": "True"
    },
    "VerySmallPerformanceBoost": {
        "FIntRenderShadowIntensity": "0",
        "FIntRenderShadowmapBias": "1",
        "FIntDebugForceMSAASamples": "-1",
        "FIntFRMMinGrassDistance": "0",
    }
}
```

**Comment by pizzaboxer** [comment] 2024-10-17 20:44
Duplicate of #1098

This was suggested a while ago, but is low-priority because of the probable complexity of it, and therefore because of uncertainty surrounding if it's worth doing knowing it'll be removed at some point.

**Closed by pizzaboxer** 2024-10-17 20:44 UTC
