### ISSUE TITLE
roblox configuring loop

### ISSUE THREAD

**Issue by frightsnights** [bloxstraplabs/bloxstrap#3157] opened 2024-10-16 07:16 UTC
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

whenever i launch roblox, it gets stuck configuring. it doesn't have this issue without bloxstrap. here's a video as an example.

https://github.com/user-attachments/assets/a2809f89-a549-4344-ac84-7ea96eb68577

### Bloxstrap Log

N/A

**Comment by diezlol** [comment] 2024-10-16 07:50
im having the same issue too right now. i tried everything
-updated to latest version of bloxstrap
-restarting my pc
-repairing the .net runtime

idk what to do about it.

**Comment by BunnyProPlayz** [comment] 2024-10-16 08:25
If you're currently enrolled in a channel with v647+ (e.g. zbeta), please wait for Bloxstrap 2.8.0 to be released. The "Configuring Roblox" loop is resolved in master, the cause is the redist.zip package being added to the Player. Refer: https://github.com/bloxstraplabs/bloxstrap/pull/3144

**Comment by xoxifor** [comment] 2024-10-16 08:32
same here

**Comment by Sgniyo** [comment] 2024-10-16 08:35
same dawg this issue is so bad

**Closed** 2024-10-16 09:58 UTC
