### ISSUE TITLE
[BUG] Roblox app loading buggy with Bloxtrap

### ISSUE THREAD

**Issue by Nonolelase** [bloxstraplabs/bloxstrap#3711] opened 2024-11-07 21:44 UTC
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v 2.8.1

### What problem did you encounter?

This problem started this morning after the automatic installation of a Roblox update. Since then, as soon as I start Roblox via Bloxtrap, I find myself facing this completely buggy application. And when I use the site, the game GUIs just never load. I have reinstalled all of Roblox and Bloxtrap several times but the problem really comes from Bloxtrap. Thank you for your help
![After Launching Roblox with Bloxtrap](https://github.com/user-attachments/assets/ddd68287-f43e-4c10-83a0-98b7d177783f)

### Bloxstrap Log

```text
N/A
```

**Comment by Wanwood1** [comment] 2024-11-07 21:47
Roblox issue, make sure the location and drive bloxstrap is installed in doesnt have any special characters, including your windows user

**Comment by Nonolelase** [comment] 2024-11-07 21:49
I checked and everything is good. Just, when I launch Roblox via Bloxtrap, I see this since the last update. Like many people apparently

**Comment by XGbzTheStorm** [comment] 2024-11-07 22:55
My Bloxtrap gives the same problem

**Comment by pizzaboxer** [comment] 2024-11-09 19:21
Duplicate of #3691

**Closed by pizzaboxer** 2024-11-09 19:21 UTC
