### ISSUE TITLE
Bloxstrap install bug

### ISSUE THREAD

**Issue by nttswannabe** [bloxstraplabs/bloxstrap#3436] opened 2024-10-24 08:08 UTC
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [x] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.0

### What problem did you encounter?

![image](https://github.com/user-attachments/assets/e3d0cba8-8ef1-4ec3-b680-2d5f21987760)
![image](https://github.com/user-attachments/assets/16a8a447-8f67-49fc-ab29-41d0c3c53355)
![image](https://github.com/user-attachments/assets/90464b38-78e9-4cfd-9f1a-669042abd2c0)

### Bloxstrap Log

```text
2024-10-24T08:04:24Z [App::OnStartup] Starting Bloxstrap v2.8.0
2024-10-24T08:04:24Z [App::OnStartup] Compiled Wednesday, 16 October 2024 at 5:44:37 PM from commit 42ffec26cf2e080fe22210305a08fcb286aeb577 (tag/v2.8.0)
2024-10-24T08:04:24Z [App::OnStartup] Loaded from %UserProfile%\Downloads\Bloxstrap-v2.8.0.exe
2024-10-24T08:04:24Z [App::OnStartup] Temp path is %UserProfile%\AppData\Local\Temp\Bloxstrap
2024-10-24T08:04:24Z [App::OnStartup] WindowsStartMenu path is %UserProfile%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs
2024-10-24T08:04:24Z [Logger::Initialize] Initializing at %UserProfile%\AppData\Local\Bloxstrap\Logs\Bloxstrap_20241024T080424Z.log
2024-10-24T08:04:24Z [Logger::Initialize] Finished initializing!
2024-10-24T08:04:24Z [JsonManager<Settings>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Settings.json...
2024-10-24T08:04:25Z [JsonManager<Settings>::Load] Loaded successfully!
2024-10-24T08:04:25Z [JsonManager<State>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\State.json...
2024-10-24T08:04:25Z [JsonManager<State>::Load] Loaded successfully!
2024-10-24T08:04:25Z [FastFlagManager::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Modifications\ClientSettings\ClientAppSettings.json...
2024-10-24T08:04:25Z [FastFlagManager::Load] Loaded successfully!
2024-10-24T08:04:25Z [FastFlagManager::SetValue] Setting of 'FLogNetwork' to '7' is pending
2024-10-24T08:04:27Z [LaunchHandler::LaunchRoblox] Initializing bootstrapper
2024-10-24T08:04:27Z [LaunchHandler::LaunchRoblox] Initializing bootstrapper dialog
2024-10-24T08:04:27Z [Bootstrapper::Run] Running bootstrapper
2024-10-24T08:04:27Z [Bootstrapper::SetStatus] Connecting to Roblox...
2024-10-24T08:04:27Z [Deployment::TestConnection<https://setup.rbxcdn.com>] Connecting...
2024-10-24T08:04:27Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/versionStudio
2024-10-24T08:04:27Z [Deployment::InitializeConnectivity] Testing connectivity...
2024-10-24T08:04:28Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/versionStudio
2024-10-24T08:04:28Z [Deployment::InitializeConnectivity] Got https://setup.rbxcdn.com as the optimal base URL
2024-10-24T08:04:28Z [Bootstrapper::Run] Connectivity check finished
2024-10-24T08:04:28Z [Bootstrapper::CheckForUpdates] Checking for updates...
2024-10-24T08:04:28Z [HttpClientLoggingHandler::ProcessRequest] GET https://api.github.com/repos/bloxstraplabs/bloxstrap/releases/latest
2024-10-24T08:04:28Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://api.github.com/repos/bloxstraplabs/bloxstrap/releases/latest
2024-10-24T08:04:28Z [Bootstrapper::CheckForUpdates] No updates found
2024-10-24T08:04:28Z [Bootstrapper::GetLatestVersionInfo] Got channel as production
2024-10-24T08:04:28Z [Deployment::GetInfo] Getting deploy info for channel production
2024-10-24T08:04:28Z [HttpClientLoggingHandler::ProcessRequest] GET https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer
2024-10-24T08:04:28Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer
2024-10-24T08:04:28Z [RegistryKeyEx::SetValueSafe] Writing '' to HKEY_CURRENT_USER\SOFTWARE\ROBLOX Corporation\Environments\RobloxPlayer\Channel\www.roblox.com
2024-10-24T08:04:28Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-4e3b062d6e584043-rbxPkgManifest.txt
2024-10-24T08:04:28Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-4e3b062d6e584043-rbxPkgManifest.txt
2024-10-24T08:04:28Z [Bootstrapper::SetStatus] Installing {product}...
2024-10-24T08:04:28Z [LaunchHandler::LaunchRoblox] Bootstrapper task has finished
2024-10-24T08:04:28Z [LaunchHandler::LaunchRoblox] An exception occurred when running the bootstrapper
2024-10-24T08:04:28Z [App::FinalizeExceptionHandling] System.IO.IOException: Access to the path '\\?\%UserProfile%\AppData\Local\Bloxstrap\Roblox\Player\content\textures\Cursors\KeyboardMouse' is denied.
   at System.IO.FileSystem.RemoveDirectoryRecursive(String fullPath, WIN32_FIND_DATA& findData, Boolean topLevel)
   at System.IO.FileSystem.RemoveDirectory(String fullPath, Boolean recursive)
   at Bloxstrap.Bootstrapper.UpgradeRoblox()
   at Bloxstrap.Bootstrapper.Run()
   at Bloxstrap.Bootstrapper.Run()
```

**Comment by nttswannabe** [comment] 2024-10-24 08:08
how do i fix this i cannot reinstall bloxstrap same error will happen

**Comment by pizzaboxer** [comment] 2024-10-25 23:21
Duplicate of #3408

**Closed by pizzaboxer** 2024-10-25 23:21 UTC
