### ISSUE TITLE
[BUG] V1 (2015) and V2 (2022) aren't functioning

### ISSUE THREAD

**Issue by offdathc** [bloxstraplabs/bloxstrap#3142] opened 2024-10-15 01:56 UTC
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

when I use either of these menus I encounter the same problem where i cant use the menu at all and everything is locked. The only possible way to close roblox is through the task manager.

https://github.com/user-attachments/assets/49351d8d-91e3-46d8-8d73-955f9ff94cdf

### Bloxstrap Log

N/A

**Comment by pizzaboxer** [comment] 2024-10-15 08:16
Duplicate of #2911

**Closed by pizzaboxer** 2024-10-15 08:16 UTC
