### ISSUE TITLE
[BUG] my bloxstrap wont open

### ISSUE THREAD

**Issue by supercoolkrish** [bloxstraplabs/bloxstrap#3471] opened 2024-10-25 18:10 UTC
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8

### What problem did you encounter?

My game wont open and instead the normal player opens

### Bloxstrap Log

```text
N/A
```

**Comment by pizzaboxer** [comment] 2024-10-25 23:28
Duplicate of #3186

**Closed by pizzaboxer** 2024-10-25 23:28 UTC
