### ISSUE TITLE
[BUG] Roblox wont open directly into a game, but only into the roblox launcher.

### ISSUE THREAD

**Issue by pellpk** [bloxstraplabs/bloxstrap#3480] opened 2024-10-25 23:14 UTC
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

2.8.0

### What problem did you encounter?

just watch the video :p
roblox wont open me into a game.
https://files.catbox.moe/5ig41z.mp4

### Bloxstrap Log

```text
N/A
```

**Comment by pellpk** [comment] 2024-10-25 23:15
bloxstrap wont open me into the game, instead it opens the "launch roblox" menu

**Comment by pizzaboxer** [comment] 2024-10-25 23:20
Duplicate of #3186. This problem is exclusive to Firefox. Alternatively, you can use a prerelease version of 2.8.1 which fixes this issue: https://github.com/bloxstraplabs/bloxstrap/actions/runs/11526434565/artifacts/2106464097

**Closed by pizzaboxer** 2024-10-25 23:20 UTC

**Comment by pellpk** [comment] 2024-10-25 23:34
ty
