### ISSUE TITLE
[BUG] Graphics slider not working

### ISSUE THREAD

**Issue by Tetrati0n** [bloxstraplabs/bloxstrap#3435] opened 2024-10-24 06:24 UTC
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.0

### What problem did you encounter?

The graphics slider in-game doesn't work.
This problem has been addressed before, but the solution (using a different browser) did not work.
https://github.com/user-attachments/assets/573619c3-3956-4048-ad54-00f530cedd51
I've tried messing around with fast flags for over an hour and can't figure it out, I've even tried deleting all my fast flags and nothing changes. 
These are my current fast flags:
`{
  "FIntDebugForceMSAASamples": "4",
  "FLogNetwork": "7",
  "DFFlagDebugRenderForceTechnologyVoxel": "True",
  "FIntNewInGameMenuPercentRollout3": "0",
  "FFlagEnableInGameMenuControls": "True",
  "FFlagEnableInGameMenuModernization": "True",
  "FFlagEnableInGameMenuChrome": "False",
  "FFlagEnableMenuControlsABTest": "False",
  "FFlagEnableV3MenuABTest3": "False",
  "FFlagEnableInGameMenuChromeABTest3": "False",
  "FFlagEnableInGameMenuChromeABTest4": "False",
  "FIntFRMMinGrassDistance": "0",
  "FIntFRMMaxGrassDistance": "0",
  "FIntRenderGrassDetailStrands": "0",
  "FIntRenderGrassHeightScaler": "0",
  "FFlagDebugGraphicsDisableDirect3D11": "True",
  "FFlagDebugGraphicsPreferVulkan": "True"
}`
![image](https://github.com/user-attachments/assets/3e899e1b-8752-4d3a-a531-9ae9e20919b2)
If anyone can help, that would be greatly appreciated <3

**Comment by bluepilledgreat** [comment] 2024-10-24 06:27
Does this happen with the regular Roblox bootstrapper?

**Comment by JohnPaulConstantinou** [comment] 2024-10-24 06:34
i have the same issue, on the official group someone says if you join set it to automatic rejoin and then make it manual it would work i tried but it worked for a few minutes then it stopped then it worked again and then idk

**Comment by amairisu** [comment] 2024-10-24 06:45
yeah sometimes the graphic sliders work and sometimes don't.

**Comment by pizzaboxer** [comment] 2024-10-24 23:31
Duplicate of #3433 - it would also help if you people answered Matt's question.

**Closed by pizzaboxer** 2024-10-24 23:31 UTC
Labels: clarification needed
